### ISSUE TITLE
Clear filters button doesn't work properly

### ISSUE THREAD

**Issue by olga-ganina** [OHDSI/AthenaUI#53]
In some cases (personally I cannot reproduce but I saw this issue from Vocabulary team) clear filters button doesn't clear all chosen filters.

**Comment by acumarav** [comment]
This PR contains fixes for the 2 filters facet issues:
1. https://drive.google.com/open?id=1uVfyI7WN3JW_KkLHTaEulV1PPp1etoJk
Clear Filter button does not remove the entered query from UI but *resets search to an empty string*
Expected behavior: Clear Filters button remove active filters but *leave search query untouched*
